name: Release

on: push

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          bodyFile: changelog/${{ github.ref_name }}.md