name: Build & Release
on: push

# 1. If we push to master with a tag, we will trigger workflow twice, use [concurrency] to prevent this
# 2. If last workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: ios
            os: macos-latest
            flutter_version: 3.3.1
            artifact_name: release-ios
            artifact_path: build/**/*.ipa
            cache_path: ios/Pods
            cache_restore_keys: ios-pods-
            cache_hash_file: .github/workflows/main.yml
          - target: macos
            os: macos-latest
            flutter_version: 3.3.1
            artifact_name: release-mac
            artifact_path: build/macos/*.zip
            cache_path: macos/Pods
            cache_restore_keys: macos-pods-
            cache_hash_file: .github/workflows/main.yml
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Cache
        uses: actions/cache@v3
        with:
          key: ${{ matrix.cache_restore_keys }}-${{ hashFiles(matrix.cache_hash_file)}}
          path: ${{ matrix.cache_path }}
          restore-keys: ${{ matrix.cache_restore_keys }}
