name: Release

on:
  push:
    branches:
      - 'main'
    tags:
      - v*

# 1. If we push to master with a tag, we will trigger workflow twice, use [concurrency] to prevent this
# 2. If last workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - run: echo checkout
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo checkout done
      - name: Upload to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          bodyFile: changelog/${{   github.ref_name }}.md